name: Deploy terraform

on:
  create:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        WORKING_DIR: ./aws_test
        AWS_REGION: us-west-2
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
    # Steps

    steps:
    - uses: actions/checkout@v3
      
    - name: Install aws-iam-authenticator
      run: |
        echo Installing aws-iam-authenticator...
        mkdir ~/aws
        curl -o ~/aws/aws-iam-authenticator \
        "https://amazon-eks.s3.${env.AWS_REGION}.amazonaws.com/\
        1.16.8/2020-04-16/bin/linux/amd64/aws-iam-authenticator"
        chmod +x ~/aws/aws-iam-authenticator
        sudo cp ~/aws/aws-iam-authenticator /usr/local/bin/aws-iam-authenticator
        
    - name: Debug
      run: |
        echo $PATH
        ls ~/aws
        aws-iam-authenticator help

    # Apply Terraform

    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.0
        
    - name: Terraform fmt
      run: terraform fmt
      working-directory: ${{ env.WORKING_DIR }}

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ env.WORKING_DIR }}

    - name: Terraform Validate
      run: terraform validate -no-color
      working-directory: ${{ env.WORKING_DIR }}

    - name: Terraform Plan
      run: terraform plan -no-color
      working-directory: ${{ env.WORKING_DIR }}
    
    - name: Terraform Apply
      run: terraform apply -no-color -auto-approve
      working-directory: ${{ env.WORKING_DIR }}
